% Problem Set 4, Question 2 - Autorepression and Noise!
% Part g
% 10/12/19
% Dynamical Equations for repressor concentration as a function of
% polymerase concentration

clear
close all

save;

%Input Section:
%Model Parameters 
P=10^-7;
kdeg=10^-5;
a=3.3;
n=3;
ki=3*10^-10;
kr=2*10^11;
kp=1.5*10^10;

%Noise generated by probability of fluctuation:
%y=Pr/dt %probability per unit time
%Pr=y*dt;




%Rss=(n*kp*P*ki*a)/(kdeg*(1+kp*P)); %Analytical solution for R concentration at
% steady state given unregulated scenario
%=2.9680e-04 M
Rss=2.9680e-04;

%kia=(((2*Rss*kdeg*kr+kdeg*(1+kp*P))^2)-((kdeg*(1+kp*P))^2))/(4*kdeg*kr*n*kp*P*a);
kia=1.1864e-05;



%Initial Condition
Ra0=Rss; % Initial repressor concentration is equal to steady state when unregulated 
Ru0=Rss;
%Integration Parameters
dt=1/60; % Length of time step in minutes
T=500000; % Length of time over which to integrate

%%%%%%%%%%%%
N=T/dt+1; %Number of time steps

%Allocate output matrices
Ru=zeros(1,N); %Repressor concentration if unregulated
Ru(1)=Ru0; % Input Initial concentration
Ra=zeros(1,N); %Repressor concentration if autorepressing
Ra(1)=Ra0; % Input Initial concentration
time=[0:dt:T]; %Create time vector
x=zeros(1,N);% Create vector for randomization
g=zeros(1,N);% Create vector for disturbance event

PB=kdeg*dt;% Probability of event occuring randomly given timescale and time increment

frac=zeros(1,N);
Noise=zeros(1,N);



%Integrate
for z=1:N-1
    x(z)=rand(1);
if x(z)<PB; 
    g(z)=1;
else g(z)=0;
    
end
    Noise(z)=randn(1);
    frac(z)=(Noise(z)*Rss*0.1*g(z));
    
end

for z=1:N-1
    dRu=(((n*kp*P*ki*a)/(1+kp*P))-kdeg*Ru(z))*dt;% find change in repressor concentration during dt, based on current repressor concentration
    Ru(z+1)=Ru(z)+dRu+frac(z);% add change in repressor concentration to current repressor concentration
    
end
for z=1:N-1
    dRa=(((n*kp*P*kia*a)/(1+kp*P+kr*Ra(z))-kdeg*Ra(z)))*dt;% find change in repressor concentration during dt, based on current repressor concentration
    Ra(z+1)=Ra(z)+dRa+frac(z);% add change in repressor concentration to current repressor concentration

end

%Plot the Results
figure %Open new figure
hold on
plot(time,Ru)
plot(time,Ra)
ylim([0,4e-4])
xlabel('time (min)')
ylabel('Repressor Concentration (M)')
hold off

lgd=legend('Repressor concentration for unregulated case','Repressor concentration for autorepressed case');

figure
histogram(Ru,'FaceColor','none','EdgeColor',[0.3010 0.7450 0.9330])
ylabel('number of occurences')
xlabel('Repressor concentration (M)')
lgd=legend('Repressor concentration for unregulated case');


figure
histogram(Ra,'FaceColor','none','EdgeColor',[0.9100    0.4100    0.1700])
ylabel('number of occurences')
xlabel('Repressor concentration (M)')
lgd=legend('Repressor concentration for autorepressed case');


Du=std(Ru);
%Standard deviation of entries in Ru= 8.1243*10^-6
Da=std(Ra);
%Standard deviation of entries in Ra= 6.5124*10^-6
